// AUTO-GENERATED from the owner's "Livre de cave" Excel by scripts/genSeed.cjs.
// Loaded as the initial demo cellar. Safe to edit, but re-running the
// generator will overwrite this file.
import type { Bottle } from "./types";

export type SeedBottle = Omit<Bottle, "id" | "createdAt" | "updatedAt">;

export const SEED_BOTTLES: SeedBottle[] = [
  {
    "name": "La Ripaille",
    "producer": "Domaine Du COLLIER",
    "appellation": "Saumur",
    "country": "France",
    "color": "rouge",
    "vintage": 2012,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "La Ripaille",
    "producer": "Domaine Du COLLIER",
    "appellation": "Saumur",
    "country": "France",
    "color": "rouge",
    "vintage": 2014,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "La Charpentrie",
    "producer": "Domaine Du COLLIER",
    "appellation": "Saumur",
    "country": "France",
    "color": "rouge",
    "vintage": 2013,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Domaine Gonon",
    "producer": "Domaine Gonon",
    "appellation": "Saint-Joseph",
    "country": "France",
    "color": "rouge",
    "vintage": 2015,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Domaine Gonon",
    "producer": "Domaine Gonon",
    "appellation": "Saint-Joseph",
    "country": "France",
    "color": "rouge",
    "vintage": 2018,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Chaupin",
    "producer": "Domaine De LA JANASSE",
    "appellation": "Châteauneuf-du-Pape",
    "country": "France",
    "color": "rouge",
    "vintage": 2015,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Clos Des Grives",
    "producer": "Domaine COMBIER",
    "appellation": "Crozes-Hermitage",
    "country": "France",
    "color": "rouge",
    "vintage": 2018,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Clos Des Papes",
    "producer": "Paul Avril",
    "appellation": "Châteauneuf-du-Pape",
    "country": "France",
    "color": "rouge",
    "vintage": 2013,
    "format": "magnum (1.5L)",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Sec",
    "producer": "Domaine Du CLOS NAUDIN - FOREAU",
    "appellation": "Vouvray",
    "country": "France",
    "color": "blanc",
    "vintage": 2016,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Deponcins",
    "producer": "Domaine François VILLARD",
    "appellation": "Condrieu",
    "country": "France",
    "color": "blanc",
    "vintage": 2019,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Deponcins",
    "producer": "Domaine François VILLARD",
    "appellation": "Condrieu",
    "country": "France",
    "color": "blanc",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Chateau Camensac",
    "producer": "Château Raymond-Lafon",
    "appellation": "Haut-Médoc",
    "country": "France",
    "cuvee": "GRAND CRU CLASSE",
    "color": "rouge",
    "vintage": 1982,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Mairlant",
    "producer": "Domaine François VILLARD",
    "appellation": "Saint-Joseph",
    "country": "France",
    "color": "rouge",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Vin Jaune",
    "producer": "Domaine De MONTBOURGEAU",
    "appellation": "L'étoile",
    "country": "France",
    "color": "doux",
    "vintage": 2012,
    "format": "620ml (clavelin)",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Brut",
    "producer": "Champagne KRUG",
    "appellation": "Champagne",
    "country": "France",
    "color": "effervescent",
    "vintage": 2008,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Dom Pérignon Cuvée Vintage",
    "producer": "Champagne MOET Et CHANDON",
    "appellation": "Champagne",
    "country": "France",
    "color": "effervescent",
    "vintage": 2010,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "La Tourtine",
    "producer": "Domaine Tempier",
    "appellation": "Bandol",
    "country": "France",
    "color": "rouge",
    "vintage": 2021,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Simon",
    "producer": "Domaine Du Clos Marie",
    "appellation": "Pic Saint-Loup",
    "country": "France",
    "color": "rouge",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Poggio Alle Mura",
    "producer": "Castello Banfi",
    "appellation": "Brunello Di Montalcino",
    "country": "Italie",
    "color": "rouge",
    "vintage": 2017,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Riesling / Schlossberg",
    "producer": "Domaine Albert MANN",
    "appellation": "Alsace Grand Cru",
    "country": "France",
    "cuvee": "GRAND CRU",
    "color": "blanc",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Demi Sec",
    "producer": "Domaine Du CLOS NAUDIN - FOREAU",
    "appellation": "Vouvray",
    "country": "France",
    "color": "blanc",
    "vintage": 2016,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Le Mont Première Trie",
    "producer": "Domaine Huet",
    "appellation": "Vouvray",
    "country": "France",
    "color": "doux",
    "vintage": 1996,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Rose Pourpre",
    "producer": "Pierre Gaillard",
    "appellation": "Côte-Rôtie",
    "country": "France",
    "color": "rouge",
    "vintage": 2017,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Rose Pourpre",
    "producer": "Pierre Gaillard",
    "appellation": "Côte-Rôtie",
    "country": "France",
    "color": "rouge",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 3,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Grande Année",
    "producer": "Champagne BOLLINGER",
    "appellation": "Champagne",
    "country": "France",
    "color": "effervescent",
    "vintage": 2012,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Château Montrose",
    "producer": "Château MONTROSE",
    "appellation": "Saint-Estèphe",
    "country": "France",
    "cuvee": "2EME CRU CLASSE",
    "color": "rouge",
    "vintage": 2008,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Domaine JAMET",
    "producer": "Domaine JAMET",
    "appellation": "Côte-Rôtie",
    "country": "France",
    "color": "rouge",
    "vintage": 2009,
    "format": "750ml",
    "quantity": 3,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Domaine CHANSON Père Et Fils",
    "producer": "Domaine CHANSON Père Et Fils",
    "appellation": "Nuits-Saint-Georges",
    "country": "France",
    "color": "rouge",
    "vintage": 2018,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Mas DAUMAS GASSAC",
    "producer": "Mas DAUMAS GASSAC",
    "appellation": "Saint-Guilhem-le-Désert",
    "country": "France",
    "color": "rouge",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Clos Du Bourg - Demi-Sec",
    "producer": "Domaine Huet",
    "appellation": "Vouvray",
    "country": "France",
    "color": "blanc",
    "vintage": 2017,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Domaine André Perret",
    "producer": "Domaine André Perret",
    "appellation": "Condrieu",
    "country": "France",
    "color": "blanc",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Calligramme",
    "producer": "Domaine De BELLIVIERE",
    "appellation": "Jasnières",
    "country": "France",
    "color": "blanc",
    "vintage": 2017,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Fronholz Riesling",
    "producer": "Domaine OSTERTAG",
    "appellation": "Alsace",
    "country": "France",
    "color": "blanc",
    "vintage": 2018,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Les Grandes Places",
    "producer": "Clusel Roch",
    "appellation": "Côte-Rôtie",
    "country": "France",
    "color": "rouge",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Heissenberg Riesling",
    "producer": "Domaine OSTERTAG",
    "appellation": "Alsace",
    "country": "France",
    "color": "blanc",
    "vintage": 2018,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Clos CANARELLI",
    "producer": "Clos CANARELLI",
    "appellation": "Corse-Figari",
    "country": "France",
    "color": "blanc",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Domaine Yves Et Mathilde GANGLOFF",
    "producer": "Domaine Yves Et Mathilde GANGLOFF",
    "appellation": "Condrieu",
    "country": "France",
    "color": "blanc",
    "vintage": 2019,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Réserve",
    "producer": "Château Des Tours",
    "appellation": "Côtes-du-Rhône",
    "country": "France",
    "color": "rouge",
    "vintage": 2016,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Le Vigne",
    "producer": "Domaine Luciano SANDRONE",
    "appellation": "Barolo",
    "country": "Italie",
    "color": "rouge",
    "vintage": 2004,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Terres Chaudes",
    "producer": "Domaine Des ROCHES NEUVES / Thierry Germain",
    "appellation": "Saumur-Champigny",
    "country": "France",
    "color": "rouge",
    "vintage": 2018,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Riesling - Schlossberg",
    "producer": "Domaine Albert MANN",
    "appellation": "Alsace Grand Cru",
    "country": "France",
    "color": "blanc",
    "vintage": 2018,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Roc De Cambes (Famille Mitjavile)",
    "producer": "Roc De Cambes (Famille Mitjavile)",
    "appellation": "Côtes De Bourg",
    "country": "France",
    "color": "rouge",
    "vintage": 2019,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Les Mémoires",
    "producer": "Domaine Des ROCHES NEUVES / Thierry Germain",
    "appellation": "Saumur-Champigny",
    "country": "France",
    "color": "rouge",
    "vintage": 2018,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Au Capceu",
    "producer": "Camin Larredya",
    "appellation": "Jurançon",
    "country": "France",
    "color": "doux",
    "vintage": 2017,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Brise Cailloux",
    "producer": "Matthieu Barret",
    "appellation": "Cornas",
    "country": "France",
    "color": "rouge",
    "vintage": 2019,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Billes Noires",
    "producer": "Matthieu Barret",
    "appellation": "Cornas",
    "country": "France",
    "color": "rouge",
    "vintage": 2016,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Chêne Marchand",
    "producer": "Domaine PINARD Vincent",
    "appellation": "Sancerre",
    "country": "France",
    "color": "blanc",
    "vintage": 2022,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Domaine De L'Anglore",
    "producer": "Domaine De L'Anglore",
    "appellation": "Tavel",
    "country": "France",
    "color": "rosé",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Domaine Des Tours",
    "producer": "Domaine Des Tours",
    "appellation": "Vin De Pays Du Vaucluse",
    "country": "France",
    "color": "rouge",
    "vintage": 2016,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Butteaux",
    "producer": "Domaine Pattes Loup - Thomas PICO",
    "appellation": "Chablis",
    "country": "France",
    "color": "blanc",
    "vintage": 2018,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Cornaline",
    "producer": "Domaine Hauvette",
    "appellation": "Les Baux De Provence",
    "country": "France",
    "color": "rouge",
    "vintage": 2010,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Les Monts Damnés",
    "producer": "Domaine Gérard Boulay",
    "appellation": "Sancerre",
    "country": "France",
    "color": "blanc",
    "vintage": 2021,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Clos De Cuminaille",
    "producer": "Pierre Gaillard",
    "appellation": "Saint-Joseph",
    "country": "France",
    "color": "rouge",
    "vintage": 2021,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Pierre Gaillard",
    "producer": "Pierre Gaillard",
    "appellation": "Côte-Rôtie",
    "country": "France",
    "color": "rouge",
    "vintage": 2021,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Clos Du Mont-Olivet (Famille Sabon)",
    "producer": "Clos Du Mont-Olivet (Famille Sabon)",
    "appellation": "Châteauneuf-du-Pape",
    "country": "France",
    "color": "rouge",
    "vintage": 2018,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Clos Rougeard \"Les Poyeux\"",
    "producer": "Domaine Foucault",
    "appellation": "Saumur-Champigny",
    "country": "France",
    "color": "rouge",
    "vintage": 2016,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Chante-Alouette",
    "producer": "M. CHAPOUTIER",
    "appellation": "Hermitage",
    "country": "France",
    "color": "blanc",
    "vintage": 2019,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Le Grand Vallon",
    "producer": "Domaine François VILLARD",
    "appellation": "Condrieu",
    "country": "France",
    "color": "blanc",
    "vintage": 2019,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Mas Amiel",
    "producer": "Mas Amiel",
    "appellation": "Maury",
    "country": "France",
    "color": "rouge",
    "vintage": 1985,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Riesling - Steingrubler",
    "producer": "Domaine Barmès-Buecher",
    "appellation": "Alsace Grand Cru",
    "country": "France",
    "color": "blanc",
    "vintage": 2021,
    "format": "magnum (1.5L)",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Fidès",
    "producer": "Eric Morgat",
    "appellation": "Savennières",
    "country": "France",
    "color": "blanc",
    "vintage": 2018,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Château Lynch Bages",
    "producer": "Château LYNCH-BAGES",
    "appellation": "Pauillac",
    "country": "France",
    "cuvee": "GRAND CRU CLASSE",
    "color": "rouge",
    "vintage": 2022,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Grand Chemarin",
    "producer": "Domaine PINARD Vincent",
    "appellation": "Sancerre",
    "country": "France",
    "color": "blanc",
    "vintage": 2022,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Vieilles Vignes",
    "producer": "Domaine VALETTE",
    "appellation": "Macon-Chaintré",
    "country": "France",
    "color": "blanc",
    "vintage": 2019,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Argile",
    "producer": "Domaine Des Ardoisières",
    "appellation": "Vin Des Allobroges",
    "country": "France",
    "color": "blanc",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Domaine De Trévallon",
    "producer": "Domaine De Trévallon",
    "appellation": "Vin De Pays Des Bouches-du-Rhône",
    "country": "France",
    "color": "rouge",
    "vintage": 2000,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "A François(e)",
    "producer": "Thibaud Boudignon",
    "appellation": "Anjou",
    "country": "France",
    "color": "blanc",
    "vintage": 2018,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Riesling - Schlossberg",
    "producer": "Domaine WEINBACH",
    "appellation": "Alsace Grand Cru",
    "country": "France",
    "cuvee": "GRAND CRU",
    "color": "blanc",
    "vintage": 2021,
    "format": "magnum (1.5L)",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Les Marsaules",
    "producer": "Domaine Du Bel Air",
    "appellation": "Bourgueil",
    "country": "France",
    "color": "rouge",
    "vintage": 2018,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Chemin De La Brune",
    "producer": "Domaine De L'Anglore",
    "appellation": "Vin De France",
    "country": "France",
    "color": "rosé",
    "vintage": 2023,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Rozeta",
    "producer": "Maxime Magnon",
    "appellation": "Corbières",
    "country": "France",
    "color": "rouge",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Giacomo BORGOGNO",
    "producer": "Giacomo BORGOGNO",
    "appellation": "Barolo",
    "country": "Italie",
    "color": "rouge",
    "vintage": 1980,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Les Blanchais",
    "producer": "Domaine Pellé",
    "appellation": "Menetou-Salon",
    "country": "France",
    "color": "blanc",
    "vintage": 2021,
    "format": "magnum (1.5L)",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Les Blanchais",
    "producer": "Domaine Pellé",
    "appellation": "Menetou-Salon",
    "country": "France",
    "color": "blanc",
    "vintage": 2022,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Riesling / Cuvée Colette",
    "producer": "Domaine WEINBACH",
    "appellation": "Alsace",
    "country": "France",
    "color": "blanc",
    "vintage": 2021,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Les Jumelles",
    "producer": "Domaine JABOULET AINE Paul",
    "appellation": "Côte-Rôtie",
    "country": "France",
    "color": "rouge",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "A360P",
    "producer": "Ostertag",
    "appellation": "Alsace",
    "country": "France",
    "color": "blanc",
    "vintage": 2018,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Clos De La Bergerie",
    "producer": "Clos De La Coulée De Serrant - Nicolas JOLY",
    "appellation": "Savennières-Roche-aux-Moines",
    "country": "France",
    "color": "blanc",
    "vintage": 2022,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "La Viallière",
    "producer": "Clusel Roch",
    "appellation": "Côte-Rôtie",
    "country": "France",
    "color": "rouge",
    "vintage": 2017,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Lur Saluces",
    "producer": "Château De FARGUES",
    "appellation": "Sauternes",
    "country": "France",
    "color": "doux",
    "vintage": 1987,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Riesling - Schlossberg",
    "producer": "Domaine WEINBACH",
    "appellation": "Alsace Grand Cru",
    "country": "France",
    "color": "blanc",
    "vintage": 2021,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Vin De Constance",
    "producer": "Klein CONSTANCIA",
    "appellation": "Afrique Du Sud",
    "country": "Afrique du Sud",
    "color": "doux",
    "vintage": 2019,
    "format": "500ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Diplomate D'empire",
    "producer": "J.C. Abbatucci",
    "appellation": "Vins De Corse",
    "country": "France",
    "color": "blanc",
    "vintage": 2022,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Gravières",
    "producer": "Jean Marc Vincent",
    "appellation": "Santenay Premier Cru",
    "country": "France",
    "color": "blanc",
    "vintage": 2021,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Riserva",
    "producer": "Giacomo BORGOGNO",
    "appellation": "Barolo",
    "country": "Italie",
    "color": "rouge",
    "vintage": 1967,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Riserva",
    "producer": "Giacomo BORGOGNO",
    "appellation": "Barolo",
    "country": "Italie",
    "color": "rouge",
    "vintage": 1969,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Les Corvées",
    "producer": "Domaine Henri RICHARD",
    "appellation": "Gevrey-chambertin",
    "country": "France",
    "color": "rouge",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Les Bressandes",
    "producer": "Domaine Des CROIX",
    "appellation": "Beaune Premier Cru",
    "country": "France",
    "color": "rouge",
    "vintage": 2016,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Clos JAUGUEYRON",
    "producer": "Clos JAUGUEYRON",
    "appellation": "Margaux",
    "country": "France",
    "color": "rouge",
    "vintage": 2016,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Village",
    "producer": "Domaine OGIER Stéphane",
    "appellation": "Côte-Rôtie",
    "country": "France",
    "color": "rouge",
    "vintage": 2020,
    "format": "magnum (1.5L)",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "La Bégou",
    "producer": "Maxime Magnon",
    "appellation": "Corbières",
    "country": "France",
    "color": "blanc",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Les Frionnes",
    "producer": "Domaine Jean Claude BACHELET Et Fils",
    "appellation": "Saint-Aubin Premier Cru",
    "country": "France",
    "color": "blanc",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Brand - Riesling",
    "producer": "Josmeyer Et Fils",
    "appellation": "Alsace Grand Cru",
    "country": "France",
    "color": "blanc",
    "vintage": 2019,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Cuvée Des Galichets",
    "producer": "Domaine De La CHEVALERIE.",
    "appellation": "Bourgueil",
    "country": "France",
    "color": "rouge",
    "vintage": 2015,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Riesling",
    "producer": "Domaine BOTT-GEYL",
    "appellation": "Alsace Grand Cru Schlossberg",
    "country": "France",
    "color": "blanc",
    "vintage": 2017,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Les 3 Quartiers",
    "producer": "Domaine Jourdan & Pichard",
    "appellation": "Chinon",
    "country": "France",
    "color": "rouge",
    "vintage": 2017,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Vaillons",
    "producer": "Jean-Paul Et Benoît Droin",
    "appellation": "Chablis Premier Cru",
    "country": "France",
    "color": "blanc",
    "vintage": 2021,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Vieilles Vignes",
    "producer": "Domaine Thibault LIGER BELAIR",
    "appellation": "Moulin-à-Vent",
    "country": "France",
    "color": "rouge",
    "vintage": 2017,
    "format": "magnum (1.5L)",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Corvées Des Vignes",
    "producer": "Domaine DUREUIL-JANTHIAL",
    "appellation": "Puligny-Montrachet",
    "country": "France",
    "color": "blanc",
    "vintage": 2018,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "VDF Bretonniere - Cuvée Parcelaire Monopole",
    "producer": "Le Domaine De La Taille Aux Loups (Jacky Blot)",
    "appellation": "Vin De France",
    "country": "France",
    "color": "blanc",
    "vintage": 2019,
    "format": "750ml",
    "quantity": 4,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Clos De La Hutte",
    "producer": "Thibaud Boudignon",
    "appellation": "Savennières",
    "country": "France",
    "color": "blanc",
    "vintage": 2018,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Clos De La Hutte",
    "producer": "Thibaud Boudignon",
    "appellation": "Savennières",
    "country": "France",
    "color": "blanc",
    "vintage": 2019,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Hauts De Husseau",
    "producer": "Le Domaine De La Taille Aux Loups (Jacky Blot)",
    "appellation": "Montlouis-sur-Loire",
    "country": "France",
    "color": "blanc",
    "vintage": 2022,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Gualibaou Du Russe",
    "producer": "Domaine VAISSE",
    "appellation": "IGP Pays D'Hérault",
    "country": "France",
    "color": "rouge",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "LES HAUTS DE HUSSEAU",
    "producer": "Le Domaine De La Taille Aux Loups (Jacky Blot)",
    "appellation": "Montlouis-sur-Loire",
    "country": "France",
    "color": "blanc",
    "vintage": 2022,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Les Laquets",
    "producer": "Domaine Cosse Maisonneuve",
    "appellation": "Cahors",
    "country": "France",
    "color": "rouge",
    "vintage": 2010,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Les Laquets",
    "producer": "Domaine Cosse Maisonneuve",
    "appellation": "Cahors",
    "country": "France",
    "color": "rouge",
    "vintage": 2016,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Gewurztraminer - Steingrubler",
    "producer": "Domaine Barmès-Buecher",
    "appellation": "Alsace Grand Cru",
    "country": "France",
    "color": "blanc",
    "vintage": 2021,
    "format": "750ml",
    "quantity": 4,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Les Genévrières",
    "producer": "Domaine Guillot-Broux",
    "appellation": "Macon - Cruzille",
    "country": "France",
    "color": "blanc",
    "vintage": 2018,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Aimer, Rêver, Prier, Se Taire...",
    "producer": "Domaine Du CLOS DES FEES (Hervé Bizeul)",
    "appellation": "IGP Côtes Catalanes",
    "country": "France",
    "color": "rouge",
    "vintage": 2018,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Ministre Imperial - Cuvée Collection",
    "producer": "J.C. Abbatucci",
    "appellation": "Vins De Corse",
    "country": "France",
    "color": "rouge",
    "vintage": 2021,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Mon Village",
    "producer": "Domaine OGIER Stéphane",
    "appellation": "Côte-Rôtie",
    "country": "France",
    "color": "rouge",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Mon Village",
    "producer": "Domaine OGIER Stéphane",
    "appellation": "Côte-Rôtie",
    "country": "France",
    "color": "rouge",
    "vintage": 2020,
    "format": "magnum (1.5L)",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Monte Bianco",
    "producer": "DOMAINE ABBATUCCI",
    "appellation": "Vin De France",
    "country": "France",
    "color": "rouge",
    "vintage": 2021,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Monte Bianco",
    "producer": "DOMAINE ABBATUCCI",
    "appellation": "Vin De France",
    "country": "France",
    "color": "rouge",
    "vintage": 2022,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Le Dragon - Riesling",
    "producer": "Josmeyer Et Fils",
    "appellation": "Alsace",
    "country": "France",
    "color": "blanc",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "La Pelerine",
    "producer": "Domaine Anne Et Jean-François Ganevat",
    "appellation": "Côtes Du Jura",
    "country": "France",
    "color": "blanc",
    "vintage": 2015,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Domaine Aux Moines - Laroche",
    "producer": "Domaine Aux Moines - Laroche",
    "appellation": "Savennières",
    "country": "France",
    "color": "blanc",
    "vintage": 2015,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Selection De Grains Nobles",
    "producer": "Domaine Philippe Delesvaux",
    "appellation": "Coteaux-du-Layon",
    "country": "France",
    "color": "blanc",
    "vintage": 2010,
    "format": "500ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Selection De Grains Nobles",
    "producer": "Domaine Philippe Delesvaux",
    "appellation": "Coteaux-du-Layon",
    "country": "France",
    "color": "blanc",
    "vintage": 2011,
    "format": "500ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Riesling",
    "producer": "Bründlmayer",
    "appellation": "Kamptal",
    "country": "Autriche",
    "color": "blanc",
    "vintage": 2019,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Castello Banfi",
    "producer": "Castello Banfi",
    "appellation": "Brunello Di Montalcino",
    "country": "Italie",
    "color": "rouge",
    "vintage": 2016,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Le Grand Vin",
    "producer": "Château De Reignac",
    "appellation": "Bordeaux Supérieur",
    "country": "France",
    "color": "rouge",
    "vintage": 2014,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Riesling - Muenchberg",
    "producer": "Domaine OSTERTAG",
    "appellation": "Alsace Grand Cru",
    "country": "France",
    "color": "blanc",
    "vintage": 2018,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Riesling - Muenchberg",
    "producer": "Domaine OSTERTAG",
    "appellation": "Alsace Grand Cru",
    "country": "France",
    "color": "blanc",
    "vintage": 2019,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Grand H",
    "producer": "Domaine Albert MANN",
    "appellation": "Alsace Pinot Noir",
    "country": "France",
    "color": "rouge",
    "vintage": 2018,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Les Genêts",
    "producer": "Damien LAUREAU",
    "appellation": "Savennières",
    "country": "France",
    "color": "blanc",
    "vintage": 2014,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Grand P",
    "producer": "Domaine Albert MANN",
    "appellation": "Alsace Pinot Noir",
    "country": "France",
    "color": "rouge",
    "vintage": 2021,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Antiche Cantine Dei Marchesi Di Barolo",
    "producer": "Marchesi Di Barolo",
    "appellation": "Barolo",
    "country": "Italie",
    "color": "rouge",
    "vintage": 1979,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Syrah La Rosine",
    "producer": "Domaine OGIER Stéphane",
    "appellation": "IGP Collines Rhodaniennes",
    "country": "France",
    "color": "rouge",
    "vintage": 2020,
    "format": "magnum (1.5L)",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "L'Ame Soeur - Syrah De Seyssuel",
    "producer": "Domaine OGIER Stéphane",
    "appellation": "IGP Collines Rhodaniennes",
    "country": "France",
    "color": "rouge",
    "vintage": 2017,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "L'Ame Soeur - Syrah De Seyssuel",
    "producer": "Domaine OGIER Stéphane",
    "appellation": "IGP Collines Rhodaniennes",
    "country": "France",
    "color": "rouge",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "La Viallière",
    "producer": "Domaine OGIER Stéphane",
    "appellation": "Côte-Rôtie",
    "country": "France",
    "color": "rouge",
    "vintage": 2016,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Fongeant",
    "producer": "Domaine OGIER Stéphane",
    "appellation": "Côte-Rôtie",
    "country": "France",
    "color": "rouge",
    "vintage": 2016,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Domaine Nicolas Rossignol",
    "producer": "Domaine Nicolas Rossignol",
    "appellation": "Volnay",
    "country": "France",
    "color": "rouge",
    "vintage": 2019,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Memorious - Pinot Noir",
    "producer": "Domaine De La Cote",
    "appellation": "Californie",
    "country": "Etats-Unis",
    "color": "rouge",
    "vintage": 2021,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Clos Jus",
    "producer": "Francois Lumpp",
    "appellation": "Givry Premier Cru",
    "country": "France",
    "color": "rouge",
    "vintage": 2018,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Clos Jus",
    "producer": "Francois Lumpp",
    "appellation": "Givry Premier Cru",
    "country": "France",
    "color": "rouge",
    "vintage": 2022,
    "format": "magnum (1.5L)",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Orthogneiss",
    "producer": "Domaine De L'Ecu",
    "appellation": "Muscadet-Sèvre-et-Maine",
    "country": "France",
    "color": "blanc",
    "vintage": 2019,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Crausot",
    "producer": "Francois Lumpp",
    "appellation": "Givry Premier Cru",
    "country": "France",
    "color": "rouge",
    "vintage": 2022,
    "format": "magnum (1.5L)",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Les Côtes",
    "producer": "Domaine Yves CUILLERON",
    "appellation": "Cornas",
    "country": "France",
    "color": "rouge",
    "vintage": 2017,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Mondeuse",
    "producer": "Dominique Belluard",
    "appellation": "Vin-de-Savoie",
    "country": "France",
    "color": "rouge",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Porto Vintage",
    "producer": "Niepoort",
    "appellation": "Porto",
    "country": "Portugal",
    "color": "rouge",
    "vintage": 2017,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Cuvée Mathieu",
    "producer": "Domaine KIRRENBOURG",
    "appellation": "Alsace Pinot Noir",
    "country": "France",
    "color": "rouge",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Venise",
    "producer": "Le Domaine De La Taille Aux Loups (Jacky Blot)",
    "appellation": "Vin De France",
    "country": "France",
    "color": "blanc",
    "vintage": 2018,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Dolia",
    "producer": "Domaine Hauvette",
    "appellation": "IGP Alpilles",
    "country": "France",
    "color": "blanc",
    "vintage": 2016,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Summus",
    "producer": "Castello Banfi",
    "appellation": "Brunello Di Montalcino",
    "country": "Italie",
    "color": "rouge",
    "vintage": 2008,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Old Wine White",
    "producer": "Mullineux Family Wines",
    "appellation": "Swartland",
    "country": "Afrique du Sud",
    "color": "blanc",
    "vintage": 2019,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Clos Des Chênes",
    "producer": "Loubet-Dewailly",
    "appellation": "Volnay Premier Cru",
    "country": "France",
    "cuvee": "1ER CRU",
    "color": "rouge",
    "vintage": 2023,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "La Serène Noire",
    "producer": "Domaine Yves Et Mathilde GANGLOFF",
    "appellation": "Côte-Rôtie",
    "country": "France",
    "color": "rouge",
    "vintage": 2017,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "La Serène Noire",
    "producer": "Domaine Yves Et Mathilde GANGLOFF",
    "appellation": "Côte-Rôtie",
    "country": "France",
    "color": "rouge",
    "vintage": 2018,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Riesling - Kastelberg",
    "producer": "Marc Kreydenweiss",
    "appellation": "Alsace Grand Cru",
    "country": "France",
    "color": "blanc",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Vin Jaune",
    "producer": "Domaine ROLET Père Et Fils",
    "appellation": "Arbois",
    "country": "France",
    "color": "blanc",
    "vintage": 2012,
    "format": "620ml (clavelin)",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Riesling - Wiebelsberg",
    "producer": "Marc Kreydenweiss",
    "appellation": "Alsace Grand Cru",
    "country": "France",
    "cuvee": "GRAND CRU",
    "color": "blanc",
    "vintage": 2017,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Vendanges Tardives / Altenbourg",
    "producer": "Domaine Albert MANN",
    "appellation": "Alsace Riesling",
    "country": "France",
    "color": "blanc",
    "vintage": 2019,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Les Terrasses De L'Empire - Christine Vernay",
    "producer": "Domaine Georges Vernay",
    "appellation": "Condrieu",
    "country": "France",
    "color": "blanc",
    "vintage": 2021,
    "format": "750ml",
    "quantity": 3,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Les Chaillées De L'Enfer - Christine Vernay",
    "producer": "Domaine Georges Vernay",
    "appellation": "Condrieu",
    "country": "France",
    "color": "blanc",
    "vintage": 2021,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Domaine De La Tour Du Bon.",
    "producer": "Domaine De La Tour Du Bon.",
    "appellation": "Bandol",
    "country": "France",
    "color": "rouge",
    "vintage": 2021,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Clos De Frémine",
    "producer": "Thibaud Boudignon",
    "appellation": "Savennières",
    "country": "France",
    "color": "blanc",
    "vintage": 2019,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Clos De Frémine",
    "producer": "Thibaud Boudignon",
    "appellation": "Savennières",
    "country": "France",
    "color": "blanc",
    "vintage": 2022,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Le Carroir",
    "producer": "Domaine Pellé",
    "appellation": "Menetou-Salon Morogues",
    "country": "France",
    "color": "blanc",
    "vintage": 2018,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Silice",
    "producer": "Domaine Des Ardoisières",
    "appellation": "Vin Des Allobroges",
    "country": "France",
    "color": "blanc",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "La Chambée",
    "producer": "Les Vins De Vienne",
    "appellation": "Condrieu",
    "country": "France",
    "color": "blanc",
    "vintage": 2018,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Pinot Noir - Altenbourg",
    "producer": "Domaine WEINBACH",
    "appellation": "Alsace",
    "country": "France",
    "color": "rouge",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Pierre Gaillard",
    "producer": "Pierre Gaillard",
    "appellation": "Saint-Joseph",
    "country": "France",
    "color": "blanc",
    "vintage": 2021,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Muscatellu",
    "producer": "Clos Nicrosi",
    "appellation": "Muscat-du-Cap-Corse",
    "country": "France",
    "color": "doux",
    "vintage": 2017,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "La Papesse",
    "producer": "Domaine Gramenon",
    "appellation": "Côtes Du Rhône",
    "country": "France",
    "color": "rouge",
    "vintage": 2021,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Thierry Et Pascale MATROT",
    "producer": "Thierry Et Pascale MATROT",
    "appellation": "Meursault",
    "country": "France",
    "color": "blanc",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Les Vignes Longues",
    "producer": "Domaine COTTENCEAU",
    "appellation": "Montagny Premier Cru",
    "country": "France",
    "color": "blanc",
    "vintage": 2018,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Grandes Jorasses - Cépage Altesse",
    "producer": "Dominique Belluard",
    "appellation": "Roussette-de-Savoie",
    "country": "France",
    "color": "blanc",
    "vintage": 2018,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Guillaume CLUSEL",
    "producer": "Guillaume CLUSEL",
    "appellation": "Saint-Joseph",
    "country": "France",
    "color": "rouge",
    "vintage": 2019,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Le Côteau De Vernon - Christine Vernay",
    "producer": "Domaine Georges Vernay",
    "appellation": "Condrieu",
    "country": "France",
    "color": "blanc",
    "vintage": 2021,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Diplomate D'empire - Cuvée Collection",
    "producer": "J.C. Abbatucci",
    "appellation": "Vins De Corse",
    "country": "France",
    "color": "blanc",
    "vintage": 2021,
    "format": "750ml",
    "quantity": 4,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Prémices",
    "producer": "Domaine De BELLIVIERE",
    "appellation": "Jasnières",
    "country": "France",
    "color": "blanc",
    "vintage": 2019,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Domaine Du CLOS NAUDIN - FOREAU",
    "producer": "Domaine Du CLOS NAUDIN - FOREAU",
    "appellation": "Vouvray",
    "country": "France",
    "color": "blanc",
    "vintage": 2018,
    "format": "750ml",
    "quantity": 3,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Domaine Du CLOS NAUDIN - FOREAU",
    "producer": "Domaine Du CLOS NAUDIN - FOREAU",
    "appellation": "Vouvray",
    "country": "France",
    "color": "blanc",
    "vintage": 2021,
    "format": "750ml",
    "quantity": 3,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "La Martinière",
    "producer": "Domaine OGEREAU",
    "appellation": "Quarts-de-Chaume",
    "country": "France",
    "color": "doux",
    "vintage": 2017,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Grand Vin De Reignac",
    "producer": "Château De Reignac",
    "appellation": "Bordeaux Supérieur",
    "country": "France",
    "color": "rouge",
    "vintage": 2014,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Riesling - Zeltinger Sonnenuhr Auslese",
    "producer": "Markus Molitor",
    "appellation": "Mosel",
    "country": "Allemagne",
    "color": "blanc",
    "vintage": 2018,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Riesling Trocken - Wehlener Sonnenuhr GG - Réserve - Alte Reben",
    "producer": "Domaine Dr. Loosen",
    "appellation": "Mosel",
    "country": "Allemagne",
    "color": "blanc",
    "vintage": 2018,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Thierry Et Pascale MATROT",
    "producer": "Thierry Et Pascale MATROT",
    "appellation": "Meursault",
    "country": "France",
    "color": "rouge",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Santa Rita Hills - Pinot Noir",
    "producer": "Sandhi Wines",
    "appellation": "Californie",
    "country": "Etats-Unis",
    "color": "rouge",
    "vintage": 2021,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Blonde Du Seigneur - Christine Vernay",
    "producer": "Domaine Georges Vernay",
    "appellation": "Côte-Rôtie",
    "country": "France",
    "color": "rouge",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Brut Nature",
    "producer": "Domaine Barmès-Buecher",
    "appellation": "Crémant D'Alsace",
    "country": "France",
    "color": "effervescent",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Mue",
    "producer": "Domaine Barmès-Buecher",
    "appellation": "Vin De France",
    "color": "rosé",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "CLOCHER - CHENIN",
    "producer": "BONNIGAL-BODET Vignerons",
    "appellation": "Touraine Amboise",
    "country": "France",
    "color": "blanc",
    "vintage": 2019,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Jardin Des Oiseaux - Pinot Noir",
    "producer": "Domaine KIRRENBOURG",
    "appellation": "Alsace",
    "country": "France",
    "color": "rouge",
    "vintage": 2019,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Extra Brut - Sparkling Wine",
    "producer": "Domaine Albert MANN",
    "appellation": "Crémant D'Alsace",
    "country": "France",
    "color": "effervescent",
    "vintage": 2021,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Meursault-Charmes",
    "producer": "Thierry Et Pascale MATROT",
    "appellation": "Meursault Premier Cru",
    "country": "France",
    "color": "blanc",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Coteau De Vernon",
    "producer": "Christine Vernay",
    "appellation": "Condrieu",
    "country": "France",
    "color": "blanc",
    "vintage": 2019,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Coteau De Vernon",
    "producer": "Christine Vernay",
    "appellation": "Condrieu",
    "country": "France",
    "color": "blanc",
    "vintage": 2021,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Les Caillerets",
    "producer": "Henri Boillot",
    "appellation": "Volnay Premier Cru",
    "country": "France",
    "color": "rouge",
    "vintage": 2019,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Domaine ROSSIGNOL-TRAPET",
    "producer": "Domaine ROSSIGNOL-TRAPET",
    "appellation": "Chambertin Grand Cru",
    "country": "France",
    "color": "rouge",
    "vintage": 2017,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Lieu Dit Les Grandes Places",
    "producer": "Les Vins De Vienne",
    "appellation": "Côte-Rôtie",
    "country": "France",
    "color": "rouge",
    "vintage": 2016,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Château PLAISANCE",
    "producer": "Château PLAISANCE",
    "appellation": "Savennières",
    "country": "France",
    "color": "blanc",
    "vintage": 2019,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Ronceray",
    "producer": "Château PLAISANCE",
    "appellation": "Anjou",
    "country": "France",
    "color": "blanc",
    "vintage": 2019,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Hommage",
    "producer": "Domaine Des BERNARDINS",
    "appellation": "Muscat De Beaumes-de-venise",
    "country": "France",
    "color": "doux",
    "vintage": null,
    "format": "500ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Les Noëls De Montbenault",
    "producer": "Thomas BATARDIERE",
    "appellation": "Vin De France",
    "color": "blanc",
    "vintage": 2022,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Brut Réserve - Méthode Traditionnelle",
    "producer": "Domaine Du CLOS NAUDIN - FOREAU",
    "appellation": "Vouvray",
    "country": "France",
    "color": "effervescent",
    "vintage": 2015,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Mise D'origine",
    "producer": "Domaine Des BERNARDINS",
    "appellation": "Muscat De Beaumes-de-venise",
    "country": "France",
    "color": "doux",
    "vintage": 2012,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Mise D'origine",
    "producer": "Domaine Des BERNARDINS",
    "appellation": "Muscat De Beaumes-de-venise",
    "country": "France",
    "color": "doux",
    "vintage": 2019,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Mise D'origine",
    "producer": "Domaine Des BERNARDINS",
    "appellation": "Muscat De Beaumes-de-venise",
    "country": "France",
    "color": "doux",
    "vintage": 2019,
    "format": "375ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Clos De La Fussière - Monopole",
    "producer": "Domaine Xavier MONNOT",
    "appellation": "Maranges Premier Cru",
    "country": "France",
    "color": "rouge",
    "vintage": 2018,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "LINA VENTURI PIERETTI",
    "producer": "LINA VENTURI PIERETTI",
    "appellation": "Vin De France",
    "color": "blanc",
    "vintage": 2019,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "GRAEME Et BOTT Julie",
    "producer": "GRAEME Et BOTT Julie",
    "appellation": "Saint-Joseph",
    "country": "France",
    "color": "blanc",
    "vintage": 2021,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Clos De Mosny - Monopole",
    "producer": "Le Domaine De La Taille Aux Loups (Jacky Blot)",
    "appellation": "Montlouis-sur-Loire",
    "country": "France",
    "color": "blanc",
    "vintage": 2019,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Classico Superiore",
    "producer": "SPERI",
    "appellation": "Valpolicella Superiore",
    "country": "Italie",
    "color": "rouge",
    "vintage": 2017,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Vintage Port",
    "producer": "Quinta De Infantado",
    "appellation": "Porto",
    "country": "Portugal",
    "color": "rouge",
    "vintage": 2017,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Cabernet Sauvignon",
    "producer": "Kathryn KENNEDY WINERY",
    "appellation": "Santa Cruz Mountains",
    "country": "Etats-Unis",
    "color": "rouge",
    "vintage": 2018,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "PETRAKOPOULOS",
    "producer": "PETRAKOPOULOS",
    "appellation": "Muscat Of Kefalonia",
    "country": "Grèce",
    "color": "doux",
    "vintage": 2019,
    "format": "500ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Organic Wine",
    "producer": "COSTABARBOL",
    "appellation": "Rioja",
    "country": "Espagne",
    "color": "rouge",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Riesling Grand Cru Furstentum",
    "producer": "Domaine Albert MANN",
    "appellation": "Alsace Grand Cru",
    "country": "France",
    "color": "blanc",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Hengst - Gewurztraminer- Cuvée François",
    "producer": "Domaine Barmès-Buecher",
    "appellation": "Alsace Grand Cru",
    "country": "France",
    "color": "blanc",
    "vintage": 2011,
    "format": "500ml",
    "quantity": 3,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Paradiso Di Cacuci",
    "producer": "Paradiso Di Montalcino",
    "appellation": "Brunello Di Montalcino",
    "country": "Italie",
    "color": "rouge",
    "vintage": 2011,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Paradiso Di Cacuci",
    "producer": "Paradiso Di Montalcino",
    "appellation": "Brunello Di Montalcino",
    "country": "Italie",
    "color": "rouge",
    "vintage": 2016,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Paradiso Di Cacuci",
    "producer": "Paradiso Di Montalcino",
    "appellation": "Brunello Di Montalcino",
    "country": "Italie",
    "color": "rouge",
    "vintage": 2018,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Famile MAYARD",
    "producer": "Famile MAYARD",
    "appellation": "Châteauneuf-du-Pape",
    "country": "France",
    "color": "rouge",
    "vintage": 2021,
    "format": "750ml",
    "quantity": 3,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Pinot Gris - Lerchenberg",
    "producer": "Marc Kreydenweiss",
    "appellation": "Alsace",
    "country": "France",
    "color": "blanc",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Pinot Blanc - Kritt",
    "producer": "Marc Kreydenweiss",
    "appellation": "Alsace",
    "country": "France",
    "color": "blanc",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Gewurztraminer - Clos Rebgarten",
    "producer": "Marc Kreydenweiss",
    "appellation": "Alsace",
    "country": "France",
    "color": "blanc",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Cru D'Alsace - La Fontaine Aux Enfants",
    "producer": "Marc Kreydenweiss",
    "appellation": "Alsace",
    "country": "France",
    "color": "blanc",
    "vintage": 2017,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Lune à Boire - Orange",
    "producer": "Charlotte & Antoine Kreydenweiss",
    "appellation": "Alsace",
    "country": "France",
    "color": "blanc",
    "vintage": 2021,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Riesling - Au Dessus De La Loi",
    "producer": "Marc Kreydenweiss",
    "appellation": "Alsace",
    "country": "France",
    "color": "blanc",
    "vintage": 2021,
    "format": "magnum (1.5L)",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Les Fremiets",
    "producer": "Henri Boillot",
    "appellation": "Volnay Premier Cru",
    "country": "France",
    "color": "rouge",
    "vintage": 2019,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "70% Roussanne - 30% Marsanne",
    "producer": "BOTT Graeme Et Julie",
    "appellation": "Saint-Joseph",
    "country": "France",
    "color": "blanc",
    "vintage": 2023,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Sylvaner - Terroir B",
    "producer": "Domaine KIRRENBOURG",
    "appellation": "Alsace",
    "country": "France",
    "color": "blanc",
    "vintage": 2019,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Riesling - Terroir S",
    "producer": "Domaine KIRRENBOURG",
    "appellation": "Alsace",
    "country": "France",
    "color": "blanc",
    "vintage": 2019,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Schlossberg",
    "producer": "Domaine KIRRENBOURG",
    "appellation": "Alsace Grand Cru",
    "country": "France",
    "color": "blanc",
    "vintage": 2019,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Gewurtztraminer Reserve",
    "producer": "Albert Boxler",
    "appellation": "Alsace",
    "country": "France",
    "color": "blanc",
    "vintage": 2017,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "La Fussière",
    "producer": "Thierry Et Pascale MATROT",
    "appellation": "Maranges Premier Cru",
    "country": "France",
    "color": "rouge",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Riesling",
    "producer": "Domaine BOTT-GEYL",
    "appellation": "Alsace Grand Cru Grafenreben",
    "country": "France",
    "color": "blanc",
    "vintage": 2015,
    "format": "500ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Riesling",
    "producer": "Domaine BOTT-GEYL",
    "appellation": "Alsace Grand Cru Grafenreben",
    "country": "France",
    "color": "blanc",
    "vintage": 2019,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Pinots - Furstentum",
    "producer": "Domaine WEINBACH",
    "appellation": "Alsace Grand Cru",
    "country": "France",
    "cuvee": "GRAND CRU",
    "color": "blanc",
    "vintage": 2021,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Furstentum - Riesling",
    "producer": "Domaine BOTT-GEYL",
    "appellation": "Alsace Grand Cru",
    "country": "France",
    "cuvee": "GRAND CRU",
    "color": "blanc",
    "vintage": 2018,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Michel Théron",
    "producer": "Clos JAUGUEYRON",
    "appellation": "Margaux",
    "country": "France",
    "color": "rouge",
    "vintage": 2019,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Michel Théron",
    "producer": "Clos JAUGUEYRON",
    "appellation": "Margaux",
    "country": "France",
    "color": "rouge",
    "vintage": 2019,
    "format": "magnum (1.5L)",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Blanc 10 Ans",
    "producer": "Vieira De Sousa",
    "appellation": "Porto",
    "country": "Portugal",
    "color": "doux",
    "vintage": null,
    "format": "500ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Tawny 10 Anos",
    "producer": "Quinta De Infantado",
    "appellation": "Porto",
    "country": "Portugal",
    "color": "doux",
    "vintage": null,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Cuvée Grand Siècle N°25",
    "producer": "Champagne LAURENT-PERRIER",
    "appellation": "Champagne",
    "country": "France",
    "color": "effervescent",
    "vintage": null,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Mas JULLIEN",
    "producer": "Mas JULLIEN",
    "appellation": "Languedoc",
    "country": "France",
    "color": "rosé",
    "vintage": 2022,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Vignes De Reuil Rosé",
    "producer": "Champagne CAZE-THIBAUT",
    "appellation": "Champagne",
    "country": "France",
    "color": "effervescent",
    "vintage": null,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Riesling - Bernkasteler Lay - Auslese",
    "producer": "Markus Molitor",
    "appellation": "Mosel",
    "country": "Allemagne",
    "color": "blanc",
    "vintage": 2015,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Lefkos",
    "producer": "SHIMA L.P WINERY",
    "appellation": "RETHYMNO",
    "country": "Grèce",
    "color": "blanc",
    "vintage": 2022,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Ohligsberg",
    "producer": "REINBOLD HAART",
    "appellation": "Mosel",
    "country": "Allemagne",
    "color": "blanc",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Kanzemer Hörecker - Riesling",
    "producer": "Weingut VON HOEVEL",
    "appellation": "Mosel",
    "country": "Allemagne",
    "color": "blanc",
    "vintage": 2022,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Oberemmeler Raul - Riesling",
    "producer": "Weingut VON HOEVEL",
    "appellation": "Mosel",
    "country": "Allemagne",
    "color": "blanc",
    "vintage": 2022,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Scharzhofberger - Riesling",
    "producer": "Weingut VON HOEVEL",
    "appellation": "Mosel",
    "country": "Allemagne",
    "color": "blanc",
    "vintage": 2022,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Clos Windsbuhl - Riesling",
    "producer": "Domaine ZIND-HUMBRECHT",
    "appellation": "Alsace",
    "country": "France",
    "color": "blanc",
    "vintage": 1996,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Aux Combottes",
    "producer": "Domaine ARLAUD",
    "appellation": "Gevrey-Chambertin Premier Cru",
    "country": "France",
    "color": "rouge",
    "vintage": 2011,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Riesling - Piesporter Grafenberg - Trocken - GG",
    "producer": "WEINGUT HAART",
    "appellation": "Mosel",
    "country": "Allemagne",
    "color": "blanc",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Riesling - Scharzhofberger Kabinett",
    "producer": "VON HOVEL",
    "appellation": "Mosel",
    "country": "Allemagne",
    "color": "blanc",
    "vintage": 2021,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "La Bulle Libre - L'Odyssée Pétillante",
    "producer": "Romain HENIN",
    "appellation": "Champagne",
    "country": "France",
    "color": "effervescent",
    "vintage": 2022,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Cru Cannubi",
    "producer": "Tenuta CARRETTA - Cascina FERRERO",
    "appellation": "Barolo",
    "country": "Italie",
    "color": "rouge",
    "vintage": 1969,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Le Domaine De La Taille Aux Loups (Jacky & J. Philippe Blot )",
    "producer": "Le Domaine De La Taille Aux Loups (Jacky & J. Philippe Blot )",
    "appellation": "Montlouis-sur-Loire",
    "country": "France",
    "color": "blanc",
    "vintage": 2022,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Venise - Cuvée Parcellaire Monopole",
    "producer": "Le Domaine De La Taille Aux Loups (Jacky & J. Philippe Blot )",
    "appellation": "Vin De France",
    "color": "blanc",
    "vintage": 2023,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Castillon",
    "producer": "Domaine De L'A - Derenoncourt",
    "appellation": "Côtes De Bordeaux",
    "country": "France",
    "color": "rouge",
    "vintage": 2022,
    "format": "750ml",
    "quantity": 3,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Domaine Jean-Marie Bouzereau",
    "producer": "Domaine Jean-Marie Bouzereau",
    "appellation": "Beaune Pertuizots Premier Cru",
    "country": "France",
    "cuvee": "1ER CRU",
    "color": "rouge",
    "vintage": 2017,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Riesling - Kreuzwingert",
    "producer": "WEINGUT HAART",
    "appellation": "Mosel",
    "country": "Allemagne",
    "color": "blanc",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Riesling - Kastelberg ( Pierre Klotz )",
    "producer": "Marc Kreydenweiss",
    "appellation": "Alsace Grand Cru",
    "country": "France",
    "color": "blanc",
    "vintage": 2019,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Pitzon",
    "producer": "Nals Margreid",
    "appellation": "Riesling",
    "country": "France",
    "color": "blanc",
    "vintage": 2023,
    "format": "750ml",
    "quantity": 3,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Anticus",
    "producer": "Nals Margreid",
    "appellation": "Merlot Cabernet Riserva",
    "country": "Italie",
    "color": "rouge",
    "vintage": 2021,
    "format": "750ml",
    "quantity": 3,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Fels",
    "producer": "Nals Margreid",
    "appellation": "Kerner",
    "country": "Italie",
    "color": "blanc",
    "vintage": 2024,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Lafot",
    "producer": "Nals Margreid",
    "appellation": "Cabernet - Riserva",
    "country": "Italie",
    "color": "rouge",
    "vintage": 2021,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Sirmian",
    "producer": "Nals Margreid",
    "appellation": "Pinot Bianco",
    "country": "Italie",
    "color": "blanc",
    "vintage": 2022,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Baronesse",
    "producer": "Nals Margreid",
    "appellation": "Moscato Giallo - Passito",
    "country": "Italie",
    "color": "blanc",
    "vintage": 2021,
    "format": "375ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Clos De La Coulée De Serrant",
    "producer": "Clos De La Coulée De Serrant - Nicolas JOLY",
    "appellation": "Savennières-Coulée-de-Serrant",
    "country": "France",
    "color": "blanc",
    "vintage": 2016,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Châteauneuf Du Pape",
    "producer": "Clos Des Papes - Paul Avril",
    "appellation": "Châteauneuf-du-Pape",
    "country": "France",
    "color": "rouge",
    "vintage": 2008,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Reflet",
    "producer": "Domaine François VILLARD",
    "appellation": "Saint-Joseph",
    "country": "France",
    "color": "rouge",
    "vintage": 2018,
    "format": "magnum (1.5L)",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Château Pontet Canet",
    "producer": "Château PONTET-CANET",
    "appellation": "Pauillac",
    "country": "France",
    "cuvee": "2EME CRU CLASSE",
    "color": "rouge",
    "vintage": 2022,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "La Moussière",
    "producer": "Domaine Alphonse MELLOT",
    "appellation": "Sancerre",
    "country": "France",
    "color": "blanc",
    "vintage": 2020,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "La Barbarine",
    "producer": "Domaine Yves Et Mathilde GANGLOFF",
    "appellation": "Côte-Rôtie",
    "country": "France",
    "color": "rouge",
    "vintage": 2016,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "La Barbarine",
    "producer": "Domaine Yves Et Mathilde GANGLOFF",
    "appellation": "Côte-Rôtie",
    "country": "France",
    "color": "rouge",
    "vintage": 2018,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Charlouise",
    "producer": "Domaine PINARD Vincent",
    "appellation": "Sancerre",
    "country": "France",
    "color": "rouge",
    "vintage": 2022,
    "format": "magnum (1.5L)",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Réserve",
    "producer": "Domaine Du CLOS NAUDIN - FOREAU",
    "appellation": "Vouvray",
    "country": "France",
    "color": "doux",
    "vintage": 2018,
    "format": "750ml",
    "quantity": 2,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Château Pontet Canet",
    "producer": "Château PONTET-CANET",
    "appellation": "Pauillac",
    "country": "France",
    "cuvee": "GRAND CRU CLASSE",
    "color": "rouge",
    "vintage": 2011,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Château De PIBARNON / Comte De Saint Victor",
    "producer": "Château De PIBARNON / Comte De Saint Victor",
    "appellation": "Bandol",
    "country": "France",
    "color": "rouge",
    "vintage": 2016,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Vendanges Entieres",
    "producer": "Domaine PINARD Vincent",
    "appellation": "Sancerre",
    "country": "France",
    "color": "rouge",
    "vintage": 2022,
    "format": "750ml",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  },
  {
    "name": "Vendanges Entieres",
    "producer": "Domaine PINARD Vincent",
    "appellation": "Sancerre",
    "country": "France",
    "color": "rouge",
    "vintage": 2022,
    "format": "magnum (1.5L)",
    "quantity": 1,
    "purchasePrice": null,
    "location": "iCave (Issy-les-Moulineaux)"
  }
];
